### ISSUE TITLE
IDE plugin showing icon 4x

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow-meta#227] opened 2019-11-24 11:15 UTC
Currently, I am seeing icons shown 4x. This is happening on master commit [e65a726](https://github.com/arrow-kt/arrow-meta/commit/e65a7269f1ebcd777b8ac0c9fb1e7fee18a202c3).

See the below-attached screenshot.

<img width="470" alt="Screenshot 2019-11-24 at 12 11 17" src="https://user-images.githubusercontent.com/12424668/69493806-b2356500-0eb3-11ea-9bf3-08c6bc94b3bc.png">

This was seen using `publishAndRunIde`. This is seen while using both gradle based projects and plain IDEA projects.

**Comment by i-walker** [comment] 2019-11-25 11:51
It is related to #228. The issue is a side effect of what #62 tries to solve. 
Currently, the idea plugin registers itself every time a project is created. Which explains your experience. We will solve this once #62 is discussed and merged. 
All our tests are green because they open solely one project in each test environment.

A workaround what we use for development is to stick with one project at a time and clean the java cache and all Gradle daemons for a fresh start-up :)

**Comment by i-walker** [comment] 2019-12-02 09:59
We will revisit this issue after KotlinConf, because it introduces mayor changes we may discuss after the conference. 
Can we remove this from the milestone @franciscodr @nomisRev

**Closed** 2020-04-08 11:00 UTC
Labels: IDEA, high-priority
