### ISSUE TITLE
Add documentation to explain AST elements in their custom scopes

### ISSUE THREAD

**Issue by ahinchman1** [arrow-kt/arrow-meta#130] opened 2019-11-13 21:40 UTC
We're building out the quote system with all as many AST elements as we can, but we will need help to go back to explain examples of what each AST element is in their custom scopes.

**Potential helpful sources:**

- the corresponding PsiElements Kotlin compiler code - see `com.kotlin.psi` package.
- the PSIViewer IntelliJ plugin can be helpful for discovering PSI elements and their associated class:
<img width="830" alt="Screen Shot 2019-11-13 at 3 46 09 PM" src="https://user-images.githubusercontent.com/6917498/68807094-ce701100-062c-11ea-9a93-0be4beceb6f7.png">

- Kotlin Academy is sometimes helpful, especially in their segment for Kotlin Programmer Dictionary. For example, one blog covers [Function Type vs Function literal vs Lambda expression vs Anonymous function](https://blog.kotlin-academy.com/kotlin-programmer-dictionary-function-type-vs-function-literal-vs-lambda-expression-vs-anonymous-edc97e8873e)

**Comment by ahinchman1** [comment] 2019-11-13 21:42
You can find which elements might need documentation by filtering PRs for `AST-scope` and does not have the `documentation` label.

![Screen Shot 2019-11-13 at 3 41 39 PM](https://user-images.githubusercontent.com/6917498/68806807-38d48180-062c-11ea-80eb-964174803a8b.png)

**Comment by raulraja** [comment] 2019-11-22 12:30
Duplicate of #198

**Comment by ahinchman1** [comment] 2019-11-22 14:50
@raulraja I apologize, the purpose of this ticket was not initially clear - while we are placing declarations for single lines for meta extensions similar to Scala's quasi-quote system, I still would like for the AST element scopes themselves to further explain what they are in Kotlin. The AST system is sometimes confusing, so I was thinking this is a nice-to-have and a great issue for first timers learning about our quote system/AST/the Kotlin compiler.  For example:

```/**
 * A template destructuring [Scope] for a [KtFunctionLiteral]
 *
 *  A function literal is a special notation to simplify how a function is defined.  There are two types of function literals in Kotlin:
 *  #### Lambda expression
 *  A lambda expression is a short way to define a function.  It tends to be more explicit than anonymous functions:
 * ```kotlin:ank:silent
 * val increment: (Int) -> Unit = { x -> x + 1 }
 * ```
 *  #### Anonymous function
 *  An anonynous function is just another way to define a function:
 * ```kotlin:ank:silent
 * val increment: (Int) -> Unit = fun(x) { x + 1 }
 * ```
 */
class FunctionLiteralScope(
  override val value: KtFunctionLiteral,
  val name: Name? = value.nameAsName,
  val blockExpression: Scope<KtBlockExpression> = Scope(value.bodyBlockExpression) // TODO KtBlockExpression scope and quote template
) : Scope<KtFunctionLiteral>(value)```

Would it be okay to open this back up?

**Closed** 2019-12-12 16:26 UTC
Labels: AST-scope, documentation, good first issue, help wanted
