### ISSUE TITLE
[BUG] "java.lang.IllegalStateException: Symbol for kotlinx.serialization.internal/LongSerializer|null[0] is unbound" exception on build with Arrow Analysis plugin

### ISSUE THREAD

**Issue by DanielChesters** [arrow-kt/arrow-meta#1021] opened 2022-03-02 17:38 UTC
**Describe the bug**
After ignore with `unsafeCall` method some issues raise by Arrow Analysis, I have this exception on build : 
```
e: java.lang.IllegalStateException: Symbol for kotlinx.serialization.internal/LongSerializer|null[0] is unbound
        at org.jetbrains.kotlin.ir.symbols.impl.IrBindablePublicSymbolBase.getOwner(IrPublicSymbolBase.kt:52)
        at org.jetbrains.kotlin.ir.types.IrTypesKt.getDefaultType(irTypes.kt:152)
        at org.jetbrains.kotlin.ir.util.KotlinLikeDumper.visitGetObjectValue(dumpKotlinLike.kt:1119)
        at org.jetbrains.kotlin.ir.util.KotlinLikeDumper.visitGetObjectValue(dumpKotlinLike.kt:115)
        at org.jetbrains.kotlin.ir.expressions.impl.IrGetObjectValueImpl.accept(IrGetObjectValueImpl.kt:32)
        at org.jetbrains.kotlin.ir.util.KotlinLikeDumper.visitVararg(dumpKotlinLike.kt:1194)
        at org.jetbrains.kotlin.ir.util.KotlinLikeDumper.visitVararg(dumpKotlinLike.kt:115)
        at org.jetbrains.kotlin.ir.expressions.impl.IrVarargImpl.accept(IrVarargImpl.kt:53)
        at org.jetbrains.kotlin.ir.util.KotlinLikeDumper.printMemberAccessExpressionWithNoIndent(dumpKotlinLike.kt:1011)
        at org.jetbrains.kotlin.ir.util.KotlinLikeDumper.printMemberAccessExpressionWithNoIndent$default(dumpKotlinLike.kt:929)
        at org.jetbrains.kotlin.ir.util.KotlinLikeDumper.visitCall(dumpKotlinLike.kt:909)
        at org.jetbrains.kotlin.ir.util.KotlinLikeDumper.visitCall(dumpKotlinLike.kt:115)
        at org.jetbrains.kotlin.ir.expressions.impl.IrCallImpl.accept(IrCallImpl.kt:47)
        at org.jetbrains.kotlin.ir.util.KotlinLikeDumper.visitReturn(dumpKotlinLike.kt:1141)
        at org.jetbrains.kotlin.ir.util.KotlinLikeDumper.visitReturn(dumpKotlinLike.kt:115)
        at org.jetbrains.kotlin.ir.expressions.impl.IrReturnImpl.accept(IrReturnImpl.kt:34)
        at org.jetbrains.kotlin.ir.util.KotlinLikeDumper.printStatementContainer(dumpKotlinLike.kt:894)
        at org.jetbrains.kotlin.ir.util.KotlinLikeDumper.printStatementContainer$default(dumpKotlinLike.kt:882)
        at org.jetbrains.kotlin.ir.util.KotlinLikeDumper.visitBlockBody(dumpKotlinLike.kt:865)
        at org.jetbrains.kotlin.ir.util.KotlinLikeDumper.visitBlockBody(dumpKotlinLike.kt:115)
        at org.jetbrains.kotlin.ir.expressions.IrBlockBody.accept(IrBody.kt:54)
        at org.jetbrains.kotlin.ir.util.KotlinLikeDumper.printSimpleFunction(dumpKotlinLike.kt:622)
        at org.jetbrains.kotlin.ir.util.KotlinLikeDumper.visitSimpleFunction(dumpKotlinLike.kt:505)
        at org.jetbrains.kotlin.ir.util.KotlinLikeDumper.visitSimpleFunction(dumpKotlinLike.kt:115)
        at org.jetbrains.kotlin.ir.declarations.IrSimpleFunction.accept(IrSimpleFunction.kt:28)
        at org.jetbrains.kotlin.ir.util.KotlinLikeDumper.visitClass(dumpKotlinLike.kt:231)
        at org.jetbrains.kotlin.ir.util.KotlinLikeDumper.visitClass(dumpKotlinLike.kt:115)
        at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:55)
        at org.jetbrains.kotlin.ir.util.KotlinLikeDumper.visitClass(dumpKotlinLike.kt:231)
        at org.jetbrains.kotlin.ir.util.KotlinLikeDumper.visitClass(dumpKotlinLike.kt:115)
        at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:55)
        at org.jetbrains.kotlin.ir.util.KotlinLikeDumper.visitFile(dumpKotlinLike.kt:157)
        at org.jetbrains.kotlin.ir.util.KotlinLikeDumper.visitFile(dumpKotlinLike.kt:115)
        at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.accept(IrFileImpl.kt:81)
        at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.acceptChildren(IrModuleFragmentImpl.kt:40)
        at org.jetbrains.kotlin.ir.util.KotlinLikeDumper.visitModuleFragment(dumpKotlinLike.kt:141)
        at org.jetbrains.kotlin.ir.util.KotlinLikeDumper.visitModuleFragment(dumpKotlinLike.kt:115)
        at org.jetbrains.kotlin.ir.declarations.impl.IrModuleFragmentImpl.accept(IrModuleFragmentImpl.kt:37)
        at org.jetbrains.kotlin.ir.util.KotlinLikeDumper.printElement(dumpKotlinLike.kt:117)
        at org.jetbrains.kotlin.ir.util.DumpKotlinLikeKt.dumpKotlinLike(dumpKotlinLike.kt:34)
        at arrow.meta.dsl.codegen.ir.IrSyntax$irDumpKotlinLike$1.invoke(IrSyntax.kt:1234)
        at arrow.meta.dsl.codegen.ir.IrSyntax$irDumpKotlinLike$1.invoke(IrSyntax.kt:1233)
        at arrow.meta.dsl.codegen.ir.IrSyntax$IrGeneration$1.generate(IrSyntax.kt:117)
        at arrow.meta.internal.registry.InternalRegistry$registerIRGeneration$1.generate(InternalRegistry.kt:324)
        at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr$lambda-1(JvmIrCodegenFactory.kt:121)
        at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:88)
        at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:146)
        at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr$default(JvmIrCodegenFactory.kt:64)
        at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.generateModule(JvmIrCodegenFactory.kt:59)
        at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:35)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:331)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:123)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:58)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:170)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:434)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:120)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:357)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally$default(IncrementalCompilerRunner.kt:299)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl$rebuild(IncrementalCompilerRunner.kt:118)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:169)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:80)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:622)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:100)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1713)
        at jdk.internal.reflect.GeneratedMethodAccessor104.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
``` 

**To Reproduce**
1. run `./gradlew build`

**Expected behavior**
The build should finish without error.

**Environment (please complete the following information):**
 - Kotlin version : 1.6.10
 - Arrow Analysis version : 2.0.2-SNAPSHOT (on 2022-03-02)

**Comment by serras** [comment] 2022-03-13 17:18
@DanielChesters do you maybe have a small part of the code which you could share with us? This looks like an internal Kotlin compiler error -- something we can do very little about -- but it would be nice to reproduce in my machine before closing the issue.

**Comment by DanielChesters** [comment] 2022-03-13 22:21
Hello,

Thank you for your reply.

Unfortunately, I cannot provide part of the code: 

* It is a private project that I cannot share code publicly.
* I do not have time to isolate the part of the code that generate this error for the moment. 

For information, the project build correctly without Arrow Meta.

**Comment by serras** [comment] 2022-03-14 06:17
Totally understandable :)

One last question: is your project using any other plugin or processor? We’ve seen weird interactions in the past with `kotlinx.serialization` and others.

**Comment by DanielChesters** [comment] 2022-03-14 09:43
Hello,

This project has sub Gradle modules. On the root module, in the `build.gradle.kts`, I have this:

``` kotlin
buildscript {
  dependencies {
    classpath("io.arrow-kt.analysis.kotlin:io.arrow-kt.analysis.kotlin.gradle.plugin:2.0.2-SNAPSHOT")
  }

  repositories {
    maven { url = uri("https://oss.sonatype.org/content/groups/public/")}
  }
}

plugins {
  kotlin("jvm") version "1.6.10"
  kotlin("kapt") version "1.6.10"
  kotlin("plugin.serialization") version "1.6.10"
  application
  jacoco
  `maven-publish`
  id("com.gorylenko.gradle-git-properties") version "2.3.1"
}

allprojects {
  apply(plugin = "kotlin")
  apply(plugin = "kotlin-kapt")
  apply(plugin = "jacoco")
[...]
```

And on the module that generate the issue, I have this in the corresponding `build.gradle.kts`:
``` kotlin
plugins {
  kotlin("plugin.serialization")
  id("org.hidetake.swagger.generator") version "2.18.2"
}

apply(plugin = "io.arrow-kt.analysis.kotlin")
```

**Comment by serras** [comment] 2022-03-15 07:58
Unfortunately this is a known problem with the Kotlin compiler, in that different plug-ins do not cooperate very well :disappointed:

**Comment by serras** [comment] 2022-03-15 08:04
I'm closing this issue because there's not much we can do in our side.

**Closed by serras** 2022-03-15 08:04 UTC
Labels: bug
